language:       generic
sudo:           required
dist:           trusty
before_install: 
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y ocaml ocaml-nox ocaml-native-compilers camlp4-extra time camlp5 ocaml-findlib
before_script:
  - WPATH=$PWD
  - cd ..        
  - git clone https://github.com/UniMath/UniMath
  - cd UniMath && make PACKAGES="Foundations Combinatorics Algebra NumberSystems CategoryTheory Ktheory" install
  - export PATH=$PATH:$PWD/sub/coq/bin/
  - cd $WPATH
script:
  - make 

