language:       generic
sudo:           required
dist:           bionic
git:
  submodules:   false

before_install: 
  - sudo apt-get update -qq
install:
  - sudo add-apt-repository -y ppa:avsm
  - sudo apt-get install -y ocaml opam aspcud time libgtk2.0-dev libgtksourceview2.0-dev emacs
  - opam init --yes --no-setup
  - eval $(opam config env)
  - opam install lablgtk camlp5 num --yes --verbose
before_script:
  - pushd ..        
  - git clone --no-checkout https://github.com/UniMath/UniMath
  - cd UniMath
  - git checkout 2dadfb61f5ef0d9805cf0eb6b80ef2beb26472d5
  - git show
  - make PACKAGES="Foundations MoreFoundations Combinatorics Algebra NumberSystems CategoryTheory Topology Ktheory PAdics" install
  - export PATH=$PATH:$PWD/sub/coq/bin/
  - popd
script:
  - make 

